# Copyright 2019 The Chromium Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

from __future__ import print_function
from __future__ import division
from __future__ import absolute_import


FATAL_ERROR = 'Pinpoint encountered a fatal internal error and cannot '\
    'continue. Please file an issue with Speed>Bisection.'

BUILD_ISOLATE_NOT_FOUND = "Buildbucket says the build completed successfully, "\
    "but Pinpoint can't find the isolate hash."

BUILD_FAILED = 'Build failed: %s'

BUILD_CANCELLED = 'Build was canceled: %s'

SWARMING_EXPIRED = 'The swarming task expired. The bots are likely '\
    'overloaded, dead, or misconfigured.'

SWARMING_TASK_ERROR = 'The swarming task failed with state "%s".'

SWARMING_TEST_FAILED = "The test failed. The test's error message was:\n%s"

SWARMING_TEST_FAILED_NO_EXCEPTION = 'The test failed. No Python exception '\
    'was found in the log.'

SWARMING_NO_BOTS = 'There are no bots available to run the test.'

READVALUE_NO_VALUES = 'Found matching histogram data, but no values '\
    'were generated by the test.'

READVALUE_NOT_FOUND = 'Could not find values matching: %s'

READVALUE_UNKNOWN_STAT = 'Unknown statistic type: %s'

READVALUE_CHART_NOT_FOUND = 'The chart "%s" is not in the results.'

READVALUE_TRACE_NOT_FOUND = 'The trace "%s" is not in the results.'

READVALUE_NO_FILE = "The test didn't produce %s."

ALL_RUNS_FAILED = 'All of the runs failed. The most common error (%d/%d runs) '\
    'was:\n%s'

RETRY_LIMIT = "Pinpoint has hit its' retry limit and will terminate this job."
RETRY_FAILED = "Pinpoint wasn't able to reschedule itself to run again."

REFRESH_FAILURE = 'An unknown failure occurred during the run.\n'\
    'Please file a bug under Speed>Bisection with this job.'

class FatalError(Exception):
  pass

class InformationalError(Exception):
  pass

class RecoverableError(Exception):
  pass
