/* Copyright 2019 The Chromium Authors. All rights reserved.
   Use of this source code is governed by a BSD-style license that can be
   found in the LICENSE file.
*/
'use strict';

// `timeserieses` is generated by ReportFetcher.
// `mergedReport` is handled by ReportSection.reducers.receiveReports.
export class ReportMerger {
  constructor(timeserieses, revisions) {
    this.timeserieses_ = timeserieses;
    this.revisions_ = revisions;
  }

  get mergedReport() {
    const rows = [];
  }
}
